version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/PathfinderEncyclopediaServer
hooks:
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 300
      runas: ubuntu