version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i pm2 -g
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'