version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install pm2 -g
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm install unit.js
  build:
    commands:
      - npm run test
      - mocha test.js
artifacts:
  files:
    - index.js
    - knexfile.js
    - database.js
    - package.json
    - appspec.yml