version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i pm2 -g
  pre-build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
      